name: Deploy

permissions:
  pages: write

on:
  push:
    branches: ["main"]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 22.x
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
          cache: "npm"
      - run: npm ci
      - run: |
          git config --global user.email "danielmschmidt92@gmail.com"
          git config --global user.name "Daniel Schmidt"
      - run: npm run build --if-present
      - run: npm run deploy
